
const getRandomActor = () => {
  const Actors = ["Bette Davis", "Meryl Streep", "Susan Sarandon",
    "Angela Lansbury", "Ingrid Bergman", "Barbara Stanwyck", "Tilda Swinton",
    "Maggie Smith", "Judi Dench", "Cate Blanchett", "Audrey Hepburn",
    "Diane Keaton", "Michelle Pfeiffer", "Sigourney Weaver", "Sally Field",
    "Grace Kelly", "Jodie Foster", "Debbie Reynolds", "Emma Thompson",
    "Helena Bonham Carter", "Julie Andrews", "Kathy Bates", "Famke Janssen",
    "Frances McDormand", "Elizabeth Taylor", "Catherine Zeta-Jones",
    "Julianne Moore", "Joan Allen", "Lauren Bacall", "Gloria Stuart",
    "Helen Mirren", "Marcia Gay Harden", "Amy Adams", "Emily Blunt",
    "Faye Dunaway", "Emily Watson", "Bernadette Peters", "Janet Leigh",
    "Rachel Weisz", "Uma Thurman", "Glenn Close", "Jessica Lange",
    "Nicole Kidman", "Naomi Watts", "Ellen Burstyn", "Talia Shire",
    "Marion Cotillard", "Jamie Lee Curtis", "Patti LuPone",
    "Christine Baranski", "Suzanne Pleshette", "Annette Bening", "Laura Linney",
    "Kate Winslet", "Virginia Madsen", "Keira Knightley", "Linda Hamilton",
    "Jennifer Connelly", "Bette Midler", "Madeline Kahn", "Maggie Gyllenhaal",
    "Karen Allen", "Catherine O'Hara", "Patricia Arquette",
    "Miranda Richardson", "Cloris Leachman", "Dianne Wiest", "Mary Steenburgen",
    "Carol Burnett", "Teri Garr", "Veronica Cartwright", "Britt Ekland",
    "Natasha Richardson", "Anne Bancroft", "Neve Campbell", "Laura Dern",
    "Holly Hunter", "Patricia Clarkson", "Anjelica Huston", "Shirley MacLaine",
    "Minnie Driver", "Sissy Spacek", "Sandy Dennis", "Geena Davis",
    "Andie MacDowell", "Catherine Keener", "Marisa Tomei", "Daryl Hannah",
    "Natalie Portman", "Viola Davis", "Rosamund Pike", "Robin Wright",
    "Julia Stiles", "Anne Hathaway", "Scarlett Johansson",
    "Bryce Dallas Howard", "Eva Green", "Vera Farmiga", "Rebecca Hall",
    "Rachel McAdams", "Jack Nicholson", "Marlon Brando", "Robert De Niro",
    "Al Pacino", "Daniel Day-Lewis", "Dustin Hoffman", "Tom Hanks",
    "Anthony Hopkins", "Paul Newman", "Denzel Washington", "Spencer Tracy",
    "Laurence Olivier", "Jack Lemmon", "Michael Caine", "James Stewart",
    "Robin Williams", "Robert Duvall", "Sean Penn", "Morgan Freeman",
    "Jeff Bridges", "Sidney Poitier", "Peter O'Toole", "Clint Eastwood",
    "Gene Hackman", "Charles Chaplin", "Ben Kingsley", "Philip Seymour Hoffman",
    "Leonardo DiCaprio", "Russell Crowe", "Kevin Spacey", "Humphrey Bogart",
    "Gregory Peck", "Clark Gable", "Gary Cooper", "George C. Scott",
    "Jason Robards", "Charles Laughton", "Anthony Quinn", "Peter Sellers",
    "James Cagney", "Peter Finch", "Henry Fonda", "Cary Grant",
    "Richard Burton", "Burt Lancaster", "William Holden", "John Wayne",
    "Kirk Douglas", "Alec Guinness", "Christopher Plummer", "Tommy Lee Jones",
    "Sean Connery", "Alan Arkin", "Christopher Walken", "Joe Pesci",
    "Ian McKellen", "Michael Douglas", "Jon Voight", "Albert Finney",
    "Geoffrey Rush", "Jeremy Irons", "Javier Bardem", "Heath Ledger",
    "Christoph Waltz", "Ralph Fiennes", "Johnny Depp", "Benicio Del Toro",
    "Jamie Foxx", "Joaquin Phoenix", "Colin Firth", "Matthew McConaughey",
    "Christian Bale", "Gary Oldman", "Edward Norton", "Brad Pitt", "Tom Cruise",
    "Matt Damon", "Hugh Jackman", "Robert Downey Jr.", "Liam Neeson",
    "Mel Gibson", "Harrison Ford", "Woody Allen", "Steve McQueen",
    "Orson Welles", "Robert Redford", "James Dean", "Charlton Heston",
    "Gene Kelly", "Robert Mitchum", "Bill Murray", "Samuel L. Jackson",
    "Jim Carrey", "Don Cheadle", "Martin Sheen", "Alan Rickman",
    "Edward G. Robinson", "Will Smith", "John Goodman", "Buster Keaton",
    "Kevin Bacon"];

  return Actors[Math.floor(Math.random() * Actors.length)];
}

export default getRandomActor;
